version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: sghss-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sghss
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./utils/generate_mock_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sghss-net

  auth-service:
    build: ./microservices/auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    depends_on:
      - mysql
    networks:
      - sghss-net

  patient-service:
    build: ./microservices/patient-service
    container_name: patient-service
    ports:
      - "8002:8000"
    depends_on:
      - mysql
    networks:
      - sghss-net

  appointment-service:
    build: ./microservices/appointment-service
    container_name: appointment-service
    ports:
      - "8003:8000"
    depends_on:
      - mysql
    networks:
      - sghss-net

volumes:
  mysql-data:

networks:
  sghss-net:
